# Generated by Django 3.1.13 on 2021-12-28 21:19

import backendCRUD.utils.ListField
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuidCompany', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nameCompany', models.CharField(max_length=50)),
                ('dscCompany', models.TextField(max_length=100)),
                ('tickerCompany', models.CharField(max_length=10)),
                ('valCompany', backendCRUD.utils.ListField.ListField(max_length=50)),
            ],
        ),
    ]
