# Generated by Django 3.1.13 on 2021-12-28 22:00

import backendCRUD.utils.ListField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='valCompany',
            field=backendCRUD.utils.ListField.ListField(),
        ),
    ]
