# Generated by Django 3.1.13 on 2021-12-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendCRUD', '0002_auto_20211228_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tickerCompany',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
